services:
  - type: web
    name: fellesino
    env: node
    buildCommand: rm -rf .svelte-kit build && pnpm install && pnpm build
    startCommand: node build/index.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: ORIGIN
        value: https://fellesino.onrender.com
